### PR TITLE
Upgrade sorbet to 0.5.9297

### PR DESCRIPTION
**Pull request by alexneverpo**
- Upgrade sorbet to the latest version
- Upgrade tapioca to the latest version
- Delete all `sorbet-typed` rbis in favor of `tapioca` generated rbis (See: tapioca [wiki](https://github.com/Shopify/tapioca/wiki/How-does-tapioca-compare-to-%22srb-rbi-gems%22-%3F))

The main reason I want to do this is that currently, the gem locks the sorbet version to be `6338`, which prevents us from upgrading sorbet version in our codebase.

### CODE REVIEW

**Comment by alexneverpo** [comment]
In addition, if this PR looks good, should I create another PR to bump the version?

**Comment by alekstorm** [comment]
Thanks, Alex. Upgrading Sorbet and Tapioca is fine, but I'm not sure about deleting the `sorbet-typed` RBIs. Contrary to the wiki link you posted, they're generated by `srb rbi sorbet-typed`, not `srb rbi gems`, and therefore are more trustworthy.

But we should probably have a more permissive version expression for Sorbet in our gemspec.

**Comment by alexneverpo** [comment]
> But we should probably have a more permissive version expression for Sorbet in our gemspec.

Yes. I set it this way on gemspec but put a fixed version on Gemfile. Thanks!

> Contrary to the wiki link you posted, they're generated by srb rbi sorbet-typed, not srb rbi gems, and therefore are more trustworthy.

From the [definition](https://github.com/sorbet/sorbet-typed#installation) of `sorbet-typed`, we can learn that it's a manual process to update the rbis of a gem and only has rough version management. Take the `activesupport` for example, it contains only two major releases, `>= 6` and. `all`. We have no way of knowing which version specifically they're referring to. https://github.com/sorbet/sorbet-typed/tree/master/lib/activesupport
The rbis copied from `sorbet-typed` would even have conflicts with the rbis generated via tapioca based on parsing the specific gems installed on your local env.
image

**Comment by alekstorm** [comment]
Whatever unblocks you is fine.

**Pull request merged**
